name: CI build

on: [push, pull_request]

jobs:

  gcc-11
    name: gcc-11 Debug
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: cmake build
      uses: gatzka/cmake-build-action@v2.0.1
      with:
        cmake_toolchain_file: ./toolchains/x86-linux-gcc-11.cmake
        cmake_build_type: Debug
